# Generated by Django 4.2 on 2023-04-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layanan_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="alamat",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="jenis_kelamin",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nik",
            field=models.BigIntegerField(null=True),
        ),
    ]
