# Generated by Django 4.2 on 2023-04-14 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("layanan_app", "0002_user_alamat_user_jenis_kelamin_user_nik"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domisili",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_domisili", models.CharField(max_length=100)),
                ("nik", models.BigIntegerField(max_length=100)),
                ("keterangan", models.TextField()),
                ("masa_berlaku", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Laporan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_laporan", models.CharField(max_length=100)),
                ("jenis_surat", models.CharField(max_length=100)),
                (
                    "is_active",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(0, "not_active"), (1, "active")],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="no_hp",
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Surat_Pindah",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_surat_pindah", models.CharField(max_length=100)),
                ("nik", models.BigIntegerField()),
                ("alamat_asal", models.TextField()),
                ("pindah_ke", models.TextField()),
                ("pengikut", models.TextField()),
                ("keterangan", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="layanan_app.laporan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Surat_Kematian",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_surat_kematian", models.CharField(max_length=100)),
                ("nik", models.BigIntegerField()),
                ("nama_wafat", models.CharField(max_length=100)),
                ("penyebab", models.CharField(max_length=100)),
                ("hari_tanggal_wafat", models.CharField(max_length=100)),
                ("pelapor", models.CharField(max_length=100)),
                ("hubungan_pelapor", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="layanan_app.laporan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Surat_Kelahiran",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_surat_kelahiran", models.CharField(max_length=100)),
                ("nik", models.BigIntegerField()),
                ("nama_bayi", models.CharField(max_length=100)),
                ("ttl", models.CharField(max_length=100)),
                ("jenis_kelamin_anak", models.CharField(max_length=100)),
                ("hari_jam_lahir", models.CharField(max_length=100)),
                ("anak_ke", models.IntegerField()),
                ("nama_ayah", models.CharField(max_length=100)),
                ("nama_ibu", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="layanan_app.laporan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sku",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_sku", models.CharField(max_length=100)),
                ("nik", models.BigIntegerField()),
                ("nama_usaha", models.CharField(max_length=100)),
                ("jenis_usaha", models.CharField(max_length=100)),
                ("alamat_usaha", models.CharField(max_length=100)),
                ("keterangan", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="layanan_app.laporan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sktm_Pend",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_sktm_pend", models.CharField(max_length=100)),
                ("nik", models.BigIntegerField()),
                ("nama_tanggungan", models.CharField(max_length=100)),
                ("jml_tanggungan", models.IntegerField()),
                ("hubungan_tanggungan", models.CharField(max_length=100)),
                ("keterangan", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="layanan_app.laporan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sktm_Kes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_sktm_kes", models.CharField(max_length=100)),
                ("nik", models.BigIntegerField()),
                ("nama_anggota_keluarga", models.CharField(max_length=100)),
                ("hubungan", models.CharField(max_length=100)),
                ("keterangan", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="layanan_app.laporan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skck",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_skck", models.CharField(max_length=100)),
                ("nik", models.BigIntegerField()),
                ("keterangan", models.TextField()),
                ("keperluan", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="layanan_app.laporan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nikah",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_nikah", models.CharField(max_length=100)),
                ("nik", models.BigIntegerField()),
                ("mempelai_pria", models.CharField(max_length=100)),
                ("mempelai_wanita", models.CharField(max_length=100)),
                ("nama_wali", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="layanan_app.laporan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="laporan",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Beda_Nama",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_beda_nama", models.CharField(max_length=100)),
                ("nik", models.BigIntegerField()),
                ("dokumen_keliru", models.CharField(max_length=100)),
                ("dokumen_benar", models.CharField(max_length=100)),
                ("keterangan", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="layanan_app.laporan",
                    ),
                ),
            ],
        ),
    ]
