# Generated by Django 4.2 on 2023-04-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("layanan_app", "0003_domisili_laporan_user_no_hp_surat_pindah_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domisili",
            name="id_laporan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="layanan_app.laporan",
            ),
        ),
    ]
