# Generated by Django 4.2 on 2023-04-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layanan_app", "0004_domisili_id_laporan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beda_nama",
            name="dokumen_benar",
            field=models.FileField(
                max_length=200, null=True, upload_to="dokumen_benar/"
            ),
        ),
        migrations.AlterField(
            model_name="beda_nama",
            name="dokumen_keliru",
            field=models.FileField(
                max_length=200, null=True, upload_to="dokumen_keliru/"
            ),
        ),
    ]
