# Generated by Django 4.2 on 2023-04-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layanan_app", "0005_alter_beda_nama_dokumen_benar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beda_nama",
            name="dokumen_pembeda",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="beda_nama",
            name="kk",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="beda_nama",
            name="ktp",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="beda_nama",
            name="surat_pengantar",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="beda_nama",
            name="surat_pernyataan",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="domisili",
            name="kk",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="domisili",
            name="ktp",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="domisili",
            name="pas_foto",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="nikah",
            name="akta_lahir",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="nikah",
            name="foto_pas_1",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="nikah",
            name="foto_pas_2",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="nikah",
            name="ijazah",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="nikah",
            name="kk",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="nikah",
            name="ktp",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="nikah",
            name="surat_belum_nikah",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="nikah",
            name="surat_persetujuan",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="nikah",
            name="surat_rt_rw",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="skck",
            name="akta",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="skck",
            name="kk",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="skck",
            name="pas_foto",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="skck",
            name="sim",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="sktm_kes",
            name="kk",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="sktm_kes",
            name="ktp",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="sktm_kes",
            name="surat_pengantar",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="sktm_pend",
            name="kk",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="sktm_pend",
            name="ktp",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="sktm_pend",
            name="surat_pengantar",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="sku",
            name="kk",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="sku",
            name="ktp",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="sku",
            name="pas_foto",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="sku",
            name="surat_pengantar",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="surat_kelahiran",
            name="kk",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="surat_kelahiran",
            name="ktp",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="surat_kelahiran",
            name="surat_dokter",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="surat_kelahiran",
            name="surat_rt_rw",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="surat_kematian",
            name="ktp_kk",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="surat_kematian",
            name="ktp_kk_pelapor",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="surat_kematian",
            name="ktp_pasangan",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="surat_kematian",
            name="surat_keterangan",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="surat_pindah",
            name="kk",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="surat_pindah",
            name="ktp",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="surat_pindah",
            name="pas_foto",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
        migrations.AddField(
            model_name="surat_pindah",
            name="surat_rt_rw",
            field=models.FileField(max_length=200, null=True, upload_to="all/"),
        ),
    ]
