# Generated by Django 4.2 on 2023-04-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layanan_app", "0009_laporan_kode_surat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laporan",
            name="is_active",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "not_active"),
                    (1, "active"),
                    (2, "progress_kepala_desa"),
                    (3, "ditolak"),
                ],
                null=True,
            ),
        ),
    ]
