# Generated by Django 4.2 on 2023-04-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layanan_app", "0010_alter_laporan_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agama",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="kewarganegaraan",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pekerjaan",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ttl",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
