# Generated by Django 4.2 on 2023-04-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layanan_app", "0011_user_agama_user_kewarganegaraan_user_pekerjaan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ttl",
            field=models.DateField(null=True),
        ),
    ]
