# Generated by Django 4.2 on 2023-04-24 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("layanan_app", "0013_laporan_id_kepala_laporan_id_petugas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Change_Password",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_change_password", models.CharField(max_length=100)),
                ("otp", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
