# Generated by Django 4.2 on 2023-05-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layanan_app", "0014_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="laporan",
            name="count_download",
            field=models.IntegerField(null=True),
        ),
    ]
